# .github/actions/secret-sharing/action.yml
name: "Secret Sharing Service"
description: "Import/export secrets between Mercury platform and authorized partners"

inputs:
  operation:
    description: "Operation to perform: import or export"
    required: true
  partner_id:
    description: "ID of the authorized partner"
    required: true
  secret_name:
    description: "Name of the secret"
    required: true
  secret_value:
    description: "Secret value (required for import)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r .github/actions/secret-sharing/requirements.txt

    - name: Run Secret Sharing Operation
      shell: bash
      run: |
        if [ "${{ inputs.operation }}" == "import" ]; then
          python .github/actions/secret-sharing/import_secret.py \
            --partner-id "${{ inputs.partner_id }}" \
            --secret-name "${{ inputs.secret_name }}" \
            --secret-value "${{ inputs.secret_value }}"
        else
          python .github/actions/secret-sharing/export_secret.py \
            --partner-id "${{ inputs.partner_id }}" \
            --secret-name "${{ inputs.secret_name }}"
        fi
