name: "Provision Secret Sharing Service"
description: "Reusable action to provision a Secret Sharing Service for a data product using Terraform."

inputs:
  product_name:
    description: "The name of the data product."
    required: true
  env:
    description: "Environment (dev, stage, prod)."
    required: true
  contact_email:
    description: "Contact email for the data product team."
    required: true
  contact_name:
    description: "Contact name for the data product team."
    required: true
  accepted_partner_ids:
    description: "JSON array of accepted partner IDs."
    required: false
    default: "[]"

outputs:
  api_gateway_url:
    description: "The URL of the provisioned API Gateway."

runs:
  using: "composite"
  steps:
    - name: Checkout Platform Repo
      uses: actions/checkout@v4
      with:
        repository: teopopescu/platform-team-repo
        ref: test/secret_sharing
        path: platform-repo

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing
      run: terraform init

    - name: Terraform Apply
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-infra
      run: terraform apply -auto-approve

    - name: Build & Push Docker Image
      shell: bash
      run: |
        IMAGE_URI="957129869060.dkr.ecr.eu-west-1.amazonaws.com/ecr-mercury-dev-euwe1-shared-service_secret-sharing:latest"
        echo "Building and pushing image: $IMAGE_URI"
        docker build --provenance=false --platform linux/arm64 -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Terraform Init
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-main
      run: terraform init

    - name: Terraform Apply
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-main
      run: |
        terraform apply -auto-approve \
          -var="product_name=${{ inputs.product_name }}" \
          -var="env=${{ inputs.env }}" \
          -var="contact_email=${{ inputs.contact_email }}" \
          -var="contact_name=${{ inputs.contact_name }}" \
          -var="accepted_partner_ids=${{ inputs.accepted_partner_ids }}"

    - name: Get API Gateway URL
      id: get_url
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing
      run: |
        URL=$(terraform output -raw api_gateway_url)
        echo "api_gateway_url=$URL" >> $GITHUB_OUTPUT