name: "Provision Secret Sharing Service"
description: "Reusable action to provision a Secret Sharing Service for a data product using Terraform."

inputs:
  product_name:
    description: "The name of the data product."
    required: true
  env:
    description: "Environment (dev, stage, prod)."
    required: true
  contact_email:
    description: "Contact email for the data product team."
    required: true
  contact_name:
    description: "Contact name for the data product team."
    required: true
  accepted_partner_ids:
    description: "JSON array of accepted partner IDs."
    required: false
    default: "[]"
  AWS_ACCESS_KEY_ID:
    description: "AWS access key ID for ECR access"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS secret access key for ECR access"
    required: true
  AWS_ACCOUNT_ID:
    description: "AWS account ID"
    required: true

outputs:
  api_gateway_url:
    description: "The URL of the provisioned API Gateway."

runs:
  using: "composite"
  steps:
    - name: Checkout Platform Repo
      uses: actions/checkout@v4
      with:
        repository: teopopescu/platform-team-repo
        ref: test/secret_sharing
        path: platform-repo

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-infra
      run: terraform init

    - name: Terraform Apply
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-infra
      run: terraform apply -auto-approve

    - name: Configure AWS credentials for ECR
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push Docker Image
      shell: bash
      working-directory: platform-repo/lambda/secret-sharing-service
      id: docker_build
      env:
        REPO_URL: 957129869060.dkr.ecr.eu-west-1.amazonaws.com/ecr-mercury-dev-euwe1-shared-service_secret-sharing
        VERSION: 0.1.4
      run: |
        echo "Building Docker image with version: $VERSION"
        FULL_IMAGE_URI="$REPO_URL:$VERSION"
        docker build --provenance=false --platform linux/amd64 -t $FULL_IMAGE_URI .
        docker push $FULL_IMAGE_URI
        echo "TF_VAR_IMAGE_URI=$FULL_IMAGE_URI" >> $GITHUB_OUTPUT

    - name: Terraform Init
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-main
      run: terraform init

    - name: Terraform Apply
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-main
      env:
        TF_VAR_IMAGE_URI: ${{ steps.docker_build.outputs.TF_VAR_IMAGE_URI }}
      run: |
        echo "Using image URI: $TF_VAR_IMAGE_URI"
        terraform apply -auto-approve \
          -var="product_name=${{ inputs.product_name }}" \
          -var="env=${{ inputs.env }}" \
          -var="contact_email=${{ inputs.contact_email }}" \
          -var="contact_name=${{ inputs.contact_name }}" \
          -var="accepted_partner_ids=${{ inputs.accepted_partner_ids }}"

    - name: Get API Gateway URL
      id: get_url
      shell: bash
      working-directory: platform-repo/terraform/secret-sharing-main
      run: |
        URL=$(terraform output -raw api_gateway_url)
        echo "api_gateway_url=$URL" >> $GITHUB_OUTPUT
        echo "API_GATEWAY_URL=$URL" >> $GITHUB_ENV