name: Provision Secret Sharing Service
on:
  push:
    branches:
      - test/secret_sharing

jobs:
  provision-secret-sharing:
    uses: ./.github/workflows/provision-secret-sharing.yml
    with:
      product_name: "data_product_123"
      env: "dev"
      contact_email: "team@example.com"
      contact_name: "Team Name"
      accepted_partner_ids: >-
        [
          {
            "id": "partner1",
            "fqdn": "partner1.example.com",
            "name": "Partner One",
            "public_key": "abc"
          },
          {
            "id": "partner99",
            "fqdn": "partner99@partnersrock.com",
            "name": "partner99",
            "public_key": "def"
          }
        ]
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      PLATFORM_REPO_TOKEN: ${{ secrets.PLATFORM_REPO_TOKEN }}

  use-api:
    runs-on: ubuntu-latest
    needs: provision-secret-sharing
    steps:
      - name: Display API Gateway URL
        run: |
            echo "Provisioned API Gateway URL: ${{ needs.provision-secret-sharing.outputs.api_gateway_url }}"

      - name: Write API Gateway URL to File
        run: echo "${{ needs.provision-secret-sharing.outputs.api_gateway_url }}" > api_gateway_url.txt

      - name: Save API Gateway URL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-gateway-url
          path: api_gateway_url.txt
